/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TestJNIVariable */

#ifndef _Included_TestJNIVariable
#define _Included_TestJNIVariable
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TestJNIVariable
 * Method:    testJNIVariable
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_TestJNIVariable_testJNIVariable
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
