/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TestJNICallback */

#ifndef _Included_TestJNICallback
#define _Included_TestJNICallback
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TestJNICallback
 * Method:    nativeMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_TestJNICallback_nativeMethod
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
